// LOCALHOST
### Get all vehicles
GET http://localhost:8080/vehicle


### Get vehicle by name
GET http://localhost:8080/vehicle/redstone


### Create vehicle
POST http://localhost:8080/vehicle HTTP/1.1
content-type: application/json

{
    "name":"Falcon 9",
    "stages":"2",
    "thrust":"1000000"
}

### Get all missions
GET http://localhost:8080/mission


### Get mission by name
GET http://localhost:8080/mission/Mercury-1


### Create mission
POST http://localhost:8080/mission HTTP/1.1
content-type: application/json
  {
    "name": "Crew Dragon Demo-2",
    "launchSite": "Cape Canaveral",
    "vehicle": "Falcon 9",
    "duration": "63d 23h 25m",
    "crew": ["Behnken","Hurley"],
    "apogee": "262",
    "destination": "Space Station"
  }



// PRODUCTION Deploy

GET https://cse341-lesson5.onrender.com/vehicle


### Get vehicle by name
GET https://cse341-lesson5.onrender.com/vehicle/redstone


### Create vehicle
POST https://cse341-lesson5.onrender.com/vehicle HTTP/1.1
content-type: application/json

{
    "name":"Falcon 9",
    "stages":"2",
    "thrust":"1000000"
}

### Get all missions
GET https://cse341-lesson5.onrender.com/mission


### Get mission by name
GET https://cse341-lesson5.onrender.com/localhost:8080/mission/Mercury-1


### Create mission
POST https://cse341-lesson5.onrender.com/mission HTTP/1.1
content-type: application/json
  {
    "name": "Crew Dragon Demo-2",
    "launchSite": "Cape Canaveral",
    "vehicle": "Falcon 9",
    "duration": "63d 23h 25m",
    "crew": ["Behnken","Hurley"],
    "apogee": "262",
    "destination": "Space Station"
  }